server:
  port: 9093

spring:
  rabbitmq:
    host: 192.168.153.198
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
