server:
  port: 9090

  # spring:
  #  redis:
  #    cluster:
  #      nodes:
  #        - 192.168.253.190:6371
  #        - 192.168.253.190:6372
  #        - 192.168.253.190:6373
  #        - 192.168.253.190:6374
  #        - 192.168.253.190:6375
  #        - 192.168.253.190:6376
  ##        - 192.168.253.197:7001
  ##        - 192.168.253.198:7003
  ##        - 192.168.253.199:7005
  ##        - 192.168.253.197:7002
  ##        - 192.168.253.198:7004
  ##        - 192.168.253.199:7006
  #      max-redirects: 1 # 获取失败 最大重定向次数
  #    jedis:
  #      pool:
  #        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
  #        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
  #        max-idle: 10      # 连接池中的最大空闲连接
  #        min-idle: 5       # 连接池中的最小空闲连接
  #    timeout: 6000
  ##    password: 123456

spring:
  datasource:
    master:
      driverclassname: com.mysql.jdbc.Driver
      jdbcurl: jdbc:mysql://192.168.253.199:3306/hsdb?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: 123456
    slave:
      driverclassname: com.mysql.jdbc.Driver
      jdbcurl: jdbc:mysql://192.168.253.199:3306/hsdb?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: 123456



#mybatis plus 设置
mybatis-plus:
  #mapper映射文件  1.mybatis plus 使用*  2.pom.xml文件配制<resources>  3.Mapper和.xml名要相同
  mapper-locations: classpath*:com/ecloud/dao/*Mapper.xml
  #实体类所在的包
  typeAliasesPackage: com.ecloud.entity
  global-config:
    #主键类型  0：数据库id自增  1：用户输入id   2：全局唯一id（数字类型唯一id）   3：全局唯一id  uuid
    id-type: 2
    #字段策略  0：忽略判断   1：非NULL判断  2：非空判断
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1

  configuration:
    #驼峰转下划线
    map-underscore-to-camel-case: true
    #开启缓存
    cache-enabled: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
