server:
  port: 9090
spring:
  rabbitmq:
    host: 192.168.253.198
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: auto
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/hsdb?useUnicode=true&characterEncoding=utf-8
